[workspace]
members = [
"app",
"gfx-api",
"gfx-wgpu",
"simulation",
"tool",
"utils",
]
default-members = [
"app",
]
resolver="2"

[workspace.dependencies]
wgpu = "0.14"
winit = "0.27"
bytemuck = { version = "1.13", features = [ "derive" ] }

anyhow = "1.0"
instant = "0.1"

glam = { version = "0.22", default-features = false, features = ["serde", "bytemuck"] }
rand = "^0.8"
