---
camera_left:
  - a
camera_right:
  - d
camera_up:
  - w
camera_down:
  - s
camera_rotate_left:
  - q
camera_rotate_right:
  - e
camera_return:
  - space
cycle_road_type:
  - c
toggle_bulldoze:
  - v
one_lane:
  - "1"
two_lane:
  - "2"
three_lane:
  - "3"
four_lane:
  - "4"
five_lane:
  - "5"
six_lane:
  - "6"
exit:
  - esc
