---
camera_left:
  - a
camera_right:
  - r
camera_up:
  - c
camera_down:
  - s
camera_rotate_left:
  - q
camera_rotate_right:
  - l
cycle_road_type:
  - d
one_lane:
  - '1'
two_lane:
  - '2'
three_lane:
  - '3'
four_lane:
  - '4'
five_lane:
  - '5'
exit:
  - esc
