---
camera_left:
  - a
camera_right:
  - r
camera_up:
  - c
camera_down:
  - s
camera_rotate_left:
  - q
camera_rotate_right:
  - l
camera_return:
  - space
cycle_curve_type:
  - m
toggle_snapping:
  - t
cycle_lane_width:
  - g
enter_bulldoze:
  - j
enter_construct:
  - d
enter_tree_plopper:
  - w
one_lane:
  - "1"
two_lane:
  - "2"
three_lane:
  - "3"
four_lane:
  - "4"
five_lane:
  - "5"
six_lane:
  - "6"
# exit:
#   - esc
esc:
  - esc
  
